## **Numpy**

**what is Numpy ?**

Numpy is Linear algebra Library python.
Used for perfroming mathematical and ligical operation an arrays.
Provides features for operation an multi-dimensional arrays and matrics in python.

**How to create numpy arrays ?**

1-D array:

In [3]:
import numpy as np
a = np.array([1,2,3,4])
print(a) 

[1 2 3 4]


2-D array:

In [4]:
import numpy as np
b = np.array([[1,2,3,],
              [5,6,7]])
print(b) 

[[1 2 3]
 [5 6 7]]


3-D array:

In [5]:
import numpy as np
b = np.array([[1,2,3],
              [5,6,7],
              [8,6,7]])
print(b) 

[[1 2 3]
 [5 6 7]
 [8 6 7]]


**Intialize an array of 'x' x 'y' DIMENSION WITH 0**

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.random.random((3,4))

array([[0.17205098, 0.19723455, 0.53396871, 0.67246582],
       [0.04395685, 0.42662442, 0.19581861, 0.96934104],
       [0.48920293, 0.92160329, 0.72804275, 0.25996234]])

**Arranging the numbers between x and y with an interval of z**

In [9]:
import numpy as np
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [11]:
np.arange(1,30,5)

array([ 1,  6, 11, 16, 21, 26])

In [12]:
np.arange(10,30,5)

array([10, 15, 20, 25])

**Arrange 'z' numbers between x and y**

In [13]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [14]:
#even numbers between 0 to 10
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [15]:
np.linspace(5,10,5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

**filling SAME number in a array dimension**

In [16]:
np.full((2,2),5)#full is function

array([[5, 5],
       [5, 5]])

In [17]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [18]:
np.full((3,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

**filling RANDOM number in a array of dimension x and y**

In [19]:
np.random.random((2,2)) # random is function

array([[0.66854849, 0.30810444],
       [0.39507804, 0.89719996]])

In [20]:
np.random.random((3,4,))

array([[0.67172741, 0.78010235, 0.56162478, 0.70955395],
       [0.17017359, 0.61344071, 0.53411142, 0.63364244],
       [0.44530974, 0.29389635, 0.63867394, 0.6249244 ]])

Inspecting the array: checking the size of array

In [21]:
a=np.array([[1,2,3],[4,5,6]]) #2 two row and three column or three element and 2 array
print(a.shape)

(2, 3)


In [22]:
b=np.array([[1,2,3,4],[4,9,5,6],[1,2,5,3]])
print(b.shape)

(3, 4)


**Inspecting the array: Resize of array**

In [23]:
a=np.array([[1,2,3],[4,5,6]]) 
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [24]:
a=np.array([[1,2,3,7],[4,8,5,6]]) 
a.shape=(4,2)
print(a)

[[1 2]
 [3 7]
 [4 8]
 [5 6]]


In [25]:
a=np.array([[1,2,3,7],[4,8,5,6]]) 
a.shape=(8,1) #trick x*y=total number of elemnts in the array
print(a)

[[1]
 [2]
 [3]
 [7]
 [4]
 [8]
 [5]
 [6]]


**Return the dimension of the array**

In [26]:
a = np.arange(24)
a
print(a.ndim)

1


In [27]:
#reshape of array
b=a.reshape(3,2,4) #trick: Calculate the factors of 24:1,2,3,4,6,12,24,
print(b.ndim)
b

3


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

**Find the number of element in an array**

In [29]:
a=np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
print(a.size)

25


In [31]:
d=np.array([[1,2,3],[1,2,3],[4,5,6]])
print(d.size)

9


In [32]:
d=np.array([[1,2,3,8],[1,8,2,3],[1,2,5,3],[4,5,5,6]])
print(d.size)

16


**Data type**

**Find the data type of an array.**

In [33]:
a=np.arange(24,dtype=float)
print(a.size)
print(a.dtype)
b=a.reshape(3,4,2)
b

24
float64


array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]])

**Numpy Array Mathematics**

Numpy Array Mathematics : **ADDITION**

In [34]:
import numpy as np
np.sum([10,30])

40

In [35]:
#using a varible parameter
a,b=10,30
np.sum([a,b])

40

In [36]:
np.sum([[10,30],[10,30]],axis=0)

array([20, 60])

In [37]:
np.sum([[10,30],[20,30]],axis=1)

array([40, 50])

In [38]:
np.sum([[10,30],[20,30]])

90

Numpy Array Mathematics : **SUBTRACTION**

In [39]:
np.subtract(10,20)

-10

**All other numpy mathamatics function**

In [40]:
np.divide(10,20) #dividing two number

0.5

In [41]:
a=np.array([2,4,6])
b=np.array([1,2,3])
np.divide(a,b)

array([2., 2., 2.])

In [42]:
np.multiply(10,20) #multiplying two number

200

In [43]:
a=np.array([2,4,6])
b=np.array([1,2,3])
np.multiply(a,b)

array([ 2,  8, 18])

In [44]:
a1=np.subtract(10,20) #subtract two number
a

array([2, 4, 6])

In [45]:
#exp,sqrt,sin,cos,log
print("Exponent:",np.exp(a1))
print("Square root:",np.sqrt(a1))
print("Sin:",np.sin(a))
print("Cos:",np.cos(a))
print("Log:",np.log(a))

Exponent: 4.5399929762484854e-05
Square root: nan
Sin: [ 0.90929743 -0.7568025  -0.2794155 ]
Cos: [-0.41614684 -0.65364362  0.96017029]
Log: [0.69314718 1.38629436 1.79175947]


C:\Users\Admin\AppData\Local\Temp\ipykernel_11592\428540516.py:3: RuntimeWarning: invalid value encountered in sqrt
  print("Square root:",np.sqrt(a1))


**Array Comparison**

In [47]:
#Element-wise camparison
a=[1,2,4]
b=[2,2,4]
c=[1,2,4]
np.equal(a,b)

array([False,  True,  True])

In [48]:
np.equal(a,c)

array([ True,  True,  True])

In [49]:
#Array-wise Camparison
a=[1,2,4]
b=[2,2,4]
c=[1,2,4]
np.array_equal(a,b)

False

In [50]:
np.array_equal(a,c)

True

**Aggregate function**

In [51]:
a=[1,2,4]
b=[2,2,4]
c=[1,2,4]
print("Sum:",np.sum(a)) #array wise sum
print("Minimum Value:",np.min(a)) #Minimum of an array
print("Mean:",np.mean(a))
print("Median:", np.median(a))
print("Coorelation Deviation:",np.corrcoef(a))
print("Standard Deviation:", np.std(a))

Sum: 7
Minimum Value: 1
Mean: 2.3333333333333335
Median: 2.0
Coorelation Deviation: 1.0
Standard Deviation: 1.247219128924647


**Concept of broadcasting**

In [52]:
a=np.array([[0,0,0],[1,2,3],[4,5,6],[5,6,7]])
b=np.array([[0,1,2]])
print("First Array:\n",a,'\n')
print("Second Array:\n",b,'\n')
print("First Array+Second Array:\n",b+b,'\n')

First Array:
 [[0 0 0]
 [1 2 3]
 [4 5 6]
 [5 6 7]] 

Second Array:
 [[0 1 2]] 

First Array+Second Array:
 [[0 2 4]] 



**Array manipulation in python:**

In [53]:
#concatenation of two array
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [54]:
#stack array row-wise:Horizantal
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [55]:
#stack array row-wise: Vertically
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
#combining column wise
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

**Spltting array**

In [57]:
x=np.arange(16).reshape(4,4)
print(x,"\n\n")
print(np.hsplit(x,2))
print("\n\n",np.hsplit(x,np.array([2,3])))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 


[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


**Indexing in python**

In [58]:
a=['y','o','g','e','s','h','','k','a','s','a','r']
a[0:7]

['y', 'o', 'g', 'e', 's', 'h', '']

In [59]:
a[4:9]

['s', 'h', '', 'k', 'a']

In [60]:
a[-11:-5] 

['o', 'g', 'e', 's', 'h', '']

**Slicing in python**

In [61]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
b[:2,:2] #[row,column]

array([[1, 2],
       [4, 5]])

In [63]:
b[1:,:2]

array([[4, 5],
       [7, 8]])

In [64]:
b[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
b[:2,1:]

array([[2, 3],
       [5, 6]])

In [66]:
b[1:,1:]

array([[5, 6],
       [8, 9]])

In [67]:
b[1:,:2]

array([[4, 5],
       [7, 8]])

In [68]:
a=np.random.randint(1,500,30).reshape(6,5) #random
a

array([[460, 165, 370, 104, 147],
       [401, 322, 440, 184, 225],
       [226, 228, 270,  40, 323],
       [415,  25, 199, 384, 221],
       [350,  38, 249, 314, 493],
       [  7,  98, 411, 356, 410]])

In [69]:
a[:4,2:]

array([[370, 104, 147],
       [440, 184, 225],
       [270,  40, 323],
       [199, 384, 221]])

In [70]:
a[2:,:3]

array([[226, 228, 270],
       [415,  25, 199],
       [350,  38, 249],
       [  7,  98, 411]])

**Advantages of numpy over list**

1.consumes less memory
2.faster
3.more convenient


In [71]:
#numpy vs list: Memory size
import numpy as np
import sys
#list
lis=range(1000)
print("Size of list:",sys.getsizeof(1)*len(lis))
#numpy
a=np.arange(1000)
print("Size of numpy:",a.size*a.itemsize)

Size of list: 28000
Size of numpy: 4000


In [72]:
#numpy vs list: speed
import time
def using_list():
  t1=time.time() #starting/initial time
  X=range(1000)
  Y=range(1000)
  z=[X[i]+Y[i] for i in range (len(X))]
  return time.time()-t1

def using_numpy():
  t2=time.time()
  a=np.arange(1000)
  b=np.arange(1000)
  z= a+b #more convient than list
  return time.time()-t1

t1=using_list()
t2=using_numpy()
print(t1,t2)
print("Numpy is this example"+str(t1/t2)+"faster!")

0.0009975433349609375 1669572712.691637
Numpy is this example5.974842110067353e-13faster!
