 **Numpy** **Assignment**

**1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a
Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return
[
 [5, 5, 5],
 [5, 5, 5],
 [5, 5, 5]
]**

In [1]:
import numpy as np

In [2]:
def fun(dim_tuple, fillnumber):
  return np.full(dim_tuple,fillnumber)
a=fun((3,3),5)

In [3]:
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

**2. Create a method that takes n Numpy arrays of same dimensions sums them and return the
answer.**

In [4]:
n=np.array([3,3])
m=np.array([3,3])
n

array([3, 3])

In [5]:
m

array([3, 3])

In [6]:
np.sum(n+m)

12

**3.Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two
numbers N and M. The method should return the top-left N X M sub matrix e.g:
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]
 top_left_sub_matrix (matrix, 2, 2) -> should return:
 [
 [1, 2]
 [4, 5]
 ]**

In [9]:
import numpy as np
x=np.arange(1,10)
b=np.reshape(x,(3,3))
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#top_left_sub_matrix
b[:2,:2]

array([[1, 2],
       [4, 5]])

**4.Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two
numbers N and M The method should return the bottom-right N X M sub matrix e.g.:
 [
 [1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 ]
sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
 [
 [5, 6]
 [8, 9]
 ]**


In [11]:
import numpy as np
x=np.arange(1,10)
b=np.reshape(x,(3,3))
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
#bottom-right N X M sub matrix 
b[1:,1:]

array([[5, 6],
       [8, 9]])

**5. Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method
should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's
standard deviation as values:
 [1, 1, 1]
solution(arr) -> should return :
 {'mean': 1.0, 'std_dev': 0.0}**

In [14]:
import numpy as np
a=np.array([1,1,1])
a
dict1={'mean':np.mean(a),'std_dev':np.std(a)}
dict1

{'mean': 1.0, 'std_dev': 0.0}

Create np array of zeros of size(2,3)

In [15]:
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

flatten 2D np array to 1D array

In [16]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
arr.ravel()

array([1, 2, 3, 4, 5, 6])

 Convert 1D np Array to 2d np array from a python list

In [17]:
arr1=np.array([1,2,3,4,5,6])
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

 Create np array and sort sort

In [18]:
arr2=np.array([1,6,2,3,5,4])
arr2.sort()
arr2

array([1, 2, 3, 4, 5, 6])

 Create a 3x3 matrix array with values ranging from 2 to 10

In [19]:
from numpy.core.fromnumeric import reshape
import numpy as np
a=np.arange(2,11)
b=reshape(a,(3,3))
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

**6.Create a numpy array having user input values and convert the integer type to the float type
of the elements of the array. For instance:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]**


In [28]:
import numpy as np
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)

Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


**7.Write a Numpy program to append values to the end of an array. For instance:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]**


In [29]:
import numpy as np
a=np.array([10,20,30])
print("Original Array")
print(a)

Original Array
[10 20 30]


In [30]:
a=np.append(a,[[40,50,60],[70,80,90]])
print("Append array")
print(a)

Append array
[10 20 30 40 50 60 70 80 90]


**8.Create two numpy arrays and add the elements of both the arrays and store the result in
sumArray**

In [31]:
a=np.array([1,2,3])
print("array 1:",a)
b=np.array([2,2,3])
print("array 2:",b)
sumArray=a+b
print("Sum of two array:",sumArray)


array 1: [1 2 3]
array 2: [2 2 3]
Sum of two array: [3 4 6]


**9.Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform 
the following tasks:
a. Extract the 1st row from the array.
b. Extract the last element from the array**

In [32]:
import numpy as np
array1 = [[30*y + 10*x for x in range(1, 4)] for y in range(3)]
a = np.squeeze(np.asarray(array1))
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [33]:
# Extract the 1st row from the array
print(a[:1])

[[10 20 30]]


In [34]:
#Extract the last element from the array
print(a[2][2])

90
